export const footerLinks = [
  { label: 'About', href: '/about' },
  { label: 'Help Center', href: '/help' },
  { label: 'Terms of Service', href: '/terms' },
  { label: 'Privacy Policy', href: '/privacy' },
  { label: 'Cookie Policy', href: '/cookie' },
  { label: 'Ads Info', href: '/ads' },
  { label: 'Blog', href: '/blog' },
  { label: 'Status', href: '/status' },
  { label: 'Careers', href: '/careers' },
  { label: 'Brand Resources', href: '/brand' },
  { label: 'Advertising', href: '/advertising' },
  { label: 'Marketing', href: '/marketing' },
  { label: 'Twitter for Business', href: '/business' },
  { label: 'Developers', href: '/developers' },
  { label: 'Directory', href: '/directory' },
  { label: 'Settings', href: '/settings' },
  { label: '© 2024 Twitter, Inc.', href: '/copyright' },
];
